### PR TITLE
Package updates

### LINKED ISSUE #204: `inplace` argument of xarray `Dataset.merge` will be deprecated in xarray 0.12 (currently 0.11.3)
https://github.com/pycalphad/pycalphad/blob/6b5e9058c878564d0e0ebfcd11402f4280a1b137/pycalphad/core/equilibrium.py#L326

### PR DESCRIPTION
**Pull request by bocklund**
* Bump and pin to SymPy==1.4: Fixed a bug where Unions and Intersections do not automatically de-nest arguments (sympy/sympy#16344) anymore. Pinning to 1.4 because pycalphad is tightly coupled to SymPy and we don't want to break user environments when SymPy 1.5 is released.
* Update CI infrastructure to test on Py2.7, 3.6, 3.7
* Updates to dask
* Updates to Xarray (closes #204), minimum version is last supported release of Python 2.7

### CODE REVIEW

**Comment by bocklund** [comment]
@richardotis all tests are passing except for the following which fails on all Mac and Linux tests (passes on Windows). Any advice on tracking down this potential regression?

https://github.com/pycalphad/pycalphad/blob/6b5e9058c878564d0e0ebfcd11402f4280a1b137/pycalphad/tests/test_equilibrium.py#L117

**Comment by richardotis** [comment]
@bocklund Looking at the build logs in https://travis-ci.org/pycalphad/pycalphad/builds/523258913 I don't see that test failure, but I do see what appears to be a compiler toolchain failure and maybe even conda installation failure. Are we looking at the same builds?

**Comment by bocklund** [comment]
Interesting. I saw these last night: https://travis-ci.org/pycalphad/pycalphad/builds/523258999

**Comment by richardotis** [comment]
https://travis-ci.org/pycalphad/pycalphad/builds/523258913 (toolchain/conda failures) - commit https://github.com/pycalphad/pycalphad/commit/09685b897dc74f02638b783654396d02ede63ba7

 https://travis-ci.org/pycalphad/pycalphad/builds/523258999 (mostly working) - commit https://github.com/pycalphad/pycalphad/commit/41832143220dfd973f8ee8a2ff0229c28792f972

**Comment by bocklund** [comment]
They are the same base on the branch, but https://github.com/pycalphad/pycalphad/commit/41832143220dfd973f8ee8a2ff0229c28792f972 is the merge commit into develop. See the compare https://github.com/pycalphad/pycalphad/commit/41832143220dfd973f8ee8a2ff0229c28792f972 that shows the base of the merge is https://github.com/pycalphad/pycalphad/commit/09685b897dc74f02638b783654396d02ede63ba7

**Comment by bocklund** [comment]
Kind of strange that they are different

**Comment by bocklund** [comment]
I think the branch is working off master, not develop. I just force pushed https://github.com/pycalphad/pycalphad/pull/211/commits/54648d9504461bad11dc7b9fa9f483eb4fa67fe8 that rebased on develop.

**Comment by richardotis** [comment]
Since gh-200 the scaling of the constraints has changed, and now the default max constraint violation is probably too low. I think bumping the value in `solver.py` from `1e-6` to maybe `1e-2` will do the trick. 

The mass and site fraction balance constraints get multiplied by `MULTIPHASE_CONSTRAINT_SCALING = 1e6` now, so the effective constraint violation for mass balance is now `1e-12`, which is too small and on the same scale as the minimum site fraction.

**Comment by richardotis** [comment]
Thanks for your efforts. Looks like all that's missing is a cyipopt package for Windows py37.

**Comment by bocklund** [comment]
@richardotis do you want to review this and push towards merging (defer packaging issues until we are closer to release)?

**Pull request merged**
