### PR TITLE
ENH: Allow solution refinement by the Ipopt solver to be disabled.

### PR DESCRIPTION
**Pull request by bocklund**

### CODE REVIEW

**Comment by richardotis** [comment]
Does it need a test?

**Comment by bocklund** [comment]
Maybe an integration test to validate that a certain point density gives a certain result? Do you have another suggestion?

**Comment by richardotis** [comment]
An integration test that exercises the code path and makes sure we return an answer without raising is fine.  We don't make any accuracy promises with this mode.

**Comment by bocklund** [comment]
I have a sketch of a test written, but this has made me realize that the chemical potentials are all 0.0. The other properties seem correct.

**Comment by bocklund** [comment]
Py3.5 tests pass due to some dependency luck, so this should just need a rebase on #192 to fix other platforms

**Pull request merged**
