### PR TITLE
FIX: sympy 1.1 compatibility

### PR DESCRIPTION
**Pull request by richardotis**
Fixes gh-105.

### CODE REVIEW

**Comment by bocklund** [comment]
Can you remind me why we are import checking rather than just `sympy >= 1.1`?

Something about python 3.4 support, right?

**Comment by richardotis** [comment]
Why break backcompat when you can keep it with a two line check?

And I think Python 3.4 support will be going away soon when IPOPT starts getting merged.

On Jul 20, 2017 2:23 PM, Brandon Bocklund <notifications@github.com> wrote:

Can you remind me why we are import checking rather than just sympy >= 1.1?

Something about python 3.4 support, right?

**Comment by bocklund** [comment]
That's fine. Still some failing tests here

**Comment by bocklund** [comment]
Looks like Mac builds are failing on travis, but everything else looks ok.

**Comment by richardotis** [comment]
`TypeError: argument is not an mpz` is an indication that gmpy2 is installed. It's purposefully excluded from the Linux-based Docker images but it's slipping into the Mac builds.

**Comment by richardotis** [comment]
Tracking issue: sympy/sympy#12895

**Comment by richardotis** [comment]
Based on separate discussion, we think this is suitable for merge. We'll work with upstream to get the issue with gmpy2 fixed.

**Pull request merged**
