### PR TITLE
DOC: Add pycalphad citation to README.rst and index.rst

### PR DESCRIPTION
**Pull request by bocklund**

### CODE REVIEW

**Comment by richardotis** [comment]
Merge when ready, please check to make sure the docs auto-update on the website after the deploy script runs on Travis.

**Comment by richardotis** [comment]
@bocklund Despite reporting error code 0, the deployment script failed: https://travis-ci.org/pycalphad/pycalphad/jobs/208386290

Can you investigate and determine whether it's py36 related?

**Comment by bocklund** [comment]
I'll take a look at it

**Comment by bocklund** [comment]
It's failing to install at
```
$ if [ -z "$DOCKER_TAG" ]; then
      pip install python-coveralls && coveralls
    else
      docker run --rm -v $(pwd):/pycalphad:rw  -it $DOCKER_USER/pycalphad:$DOCKER_TAG /bin/sh -c "cd /pycalphad ; pip install python-coveralls && coveralls"
    fi
    
Collecting python-coveralls
  Downloading python_coveralls-2.9.0-py2.py3-none-any.whl
Collecting coverage==4.0.3 (from python-coveralls)
  Downloading coverage-4.0.3.tar.gz (354kB)
    100% |████████████████████████████████| 358kB 1.3MB/s 
Requirement already satisfied: six in /work/miniconda/envs/condaenv/lib/python3.6/site-packages (from python-coveralls)
Requirement already satisfied: requests in /work/miniconda/envs/condaenv/lib/python3.6/site-packages (from python-coveralls)
Requirement already satisfied: PyYAML in /work/miniconda/envs/condaenv/lib/python3.6/site-packages (from python-coveralls)
Building wheels for collected packages: coverage
  Running setup.py bdist_wheel for coverage ... \/done
  Stored in directory: /root/.cache/pip/wheels/66/32/43/e100f8ea009874cbfbb54c95e06425e89af0bde2a61560a886
Successfully built coverage
Installing collected packages: coverage, python-coveralls
  Found existing installation: coverage 4.3.4
    Uninstalling coverage-4.3.4:
      Successfully uninstalled coverage-4.3.4
Successfully installed coverage-4.0.3 python-coveralls-2.9.0
Traceback (most recent call last):
  File "/work/miniconda/envs/condaenv/bin/coveralls", line 11, in <module>
    sys.exit(wear())
  File "/work/miniconda/envs/condaenv/lib/python3.6/site-packages/coveralls/__init__.py", line 95, in wear
    parallel=args.parallel,
  File "/work/miniconda/envs/condaenv/lib/python3.6/site-packages/coveralls/api.py", line 7, in post
    json_file = build_file(repo_token, service_job_id, service_name, git, source_files, parallel)
  File "/work/miniconda/envs/condaenv/lib/python3.6/site-packages/coveralls/api.py", line 22, in build_file
    return StringIO(json.dumps(content))
  File "/work/miniconda/envs/condaenv/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/work/miniconda/envs/condaenv/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/work/miniconda/envs/condaenv/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/work/miniconda/envs/condaenv/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

I wasn't able to reproduce this locally. I saw something similar when doing py36 stuff in another repo, so I think this is indeed related to py36.

Though I think this should not have impacted the deployment script being run because that was just before this error.

**Comment by bocklund** [comment]
@richardotis This is still failing. It looks to be fixed [upstream in python-coveralls](https://github.com/z4r/python-coveralls/pull/57), but there hasn't been a new release on PyPI with that change yet. Should we just roll back to 3.5 until that's propagated through?

**Comment by richardotis** [comment]
Because python-coveralls is part of our CI infrastructure and doesn't go into the release artifact, I'm comfortable pinning to a commit on python-coveralls master for now. Something like `pip install git+git://git@github.com:z4r/python-coveralls.git@00c6270e4a36690c427bbf28aac4859728c89765`

**Comment by richardotis** [comment]
So it turns out installing `python-coveralls` isn't even necessary. We are using `coveralls-python`, which is just `coveralls` on PyPI.

**Pull request merged**
